import './globals.css';
import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { League_Spartan } from 'next/font/google';
import React from 'react';
import Footer from "./components/Footer";

const leagueSpartan = League_Spartan({ weight: ['700', '600', '400', '300'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
